apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
        - name: auth-service
          image: jerom05/auth-service
          env:
            - name: db_url
              valueFrom:
                secretKeyRef:
                  name: my-secret
                  key: db_url
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: my-secret
                  key: JWT_KEY
---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
spec:
  selector:
    app: auth-service
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
