name: tests-payments

on:
  pull_request:
    paths:
      - 'payment-service/**'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      STRIPE_SECRET_KEY: ${{ secrets.STRIPE_SECRET_KEY }}
    steps:
      - uses: actions/checkout@v2
      - run: cd payment-service && npm install && npm run test:ci